var trip_data = [
{"lat" : 48.215567, 
 "lon" : 16.354645, 
 "name" : "Vienna, Austria",
 "country" : "040",
 "posts" : {}},
{"lat" : 59.334823, 
 "lon" : 18.051397, 
 "country" : "752",
 "name" : "Stockholm, Sweden",
 "posts" : {}},
{"lat" : 68.349822, 
 "lon" : 18.829744,
 "name" : "Abisko, Sweden",
 "country" : "752",
 "posts" : {
 "Nature" : "https://twosundowners.com/fjallraven_classic/",
 "Gallery" : "https://twosundowners.com/photo-Gallery/Gallery/fjallraven-classic-sweden#album"}},
{"lat" : 68.401975,
 "lon" : 15.028818,
 "name" : "Lofoten, Norway",
 "country" : "578",
 "posts" : {
 "Nature": "https://twosundowners.com/lofoten/",
 "Gallery" : "https://twosundowners.com/photo-Gallery/Gallery/lofoten/#album"}},
{"lat" : 49.220593, 
 "lon" : 18.725948, 
 "name" : "Zilina, Slovakia",
 "country" : "703",
 "posts" : {"Gallery" : "https://twosundowners.com/photo-Gallery/Gallery/slovakia/#album"}},
{"lat" : 48.769299, 
 "lon" : 17.866317, 
 "name" : "Zelena Voda, Slovakia",
 "country" : "703",
 "posts" : {
 "Climbing" : "https://twosundowners.com/Climbing-slovakia/",
 "Gallery" : "https://twosundowners.com/photo-Gallery/Gallery/slovakia/#album"}},
{"lat" : 49.089275,
 "lon" : 19.608975, 
 "name" : "Liptovsky Mikulas, Slovakia",
 "country" : "703",
 "posts" : {
 "Climbing" : "https://twosundowners.com/Climbing-slovakia/",
 "Running" : "https://twosundowners.com/slovak-Running/",
 "Gallery" : "https://twosundowners.com/photo-Gallery/Gallery/slovakia/#album"}},
{"lat" : 48.964045,
 "lon" : 20.385249, 
 "name" : "Podlesok, Slovakia",
 "country" : "703",
 "posts" : 
 {"Climbing" : "https://twosundowners.com/Climbing-slovakia/",
 "Running" : "https://twosundowners.com/slovak-Running/",
 "Gallery" : "https://twosundowners.com/photo-Gallery/Gallery/slovakia/#album"}},
{"lat" : 47.662625,
 "lon" : 23.558505,
 "name" : "Baia Mare, Romania",
 "country" : "642",
 "posts" : {
 "Climbing" : "https://twosundowners.com/Climbing-in-romania/"}},
{"lat" : 46.779538,
 "lon" : 23.608950, 
 "name" : "Cluj-Napoca, Romania",
 "country" : "642",
 "posts" : {
 "Climbing" : "https://twosundowners.com/Climbing-in-romania/",
 "City" : "https://twosundowners.com/cluj/",
 "Food" : "https://twosundowners.com/cluj/",
 "Gallery" : "https://twosundowners.com/photo-Gallery/Gallery/baia-mare/#album"}},
{"lat" : 46.217893,
 "lon" : 24.788900, 
 "name" : "Sighisoara, Romania",
 "country" : "642",
 "posts" : {"Gallery" : "https://twosundowners.com/photo-Gallery/Gallery/sighisoara/#album"}
 },
{"lat" : 45.514474, 
 "lon" : 25.367078, 
 "name" : "Bran, Romania",
 "country" : "642",
 "posts" : {
 "Climbing" : "https://twosundowners.com/Climbing-in-romania/"}},
{"lat" : 45.652937, 
 "lon" : 25.602984, 
 "name" : "Brasov, Romania",
 "country" : "642",
 "posts" : {
 "General" : "https://twosundowners.com/road-to-bulgaria/",
 "Climbing" : "https://twosundowners.com/Climbing-in-romania/",
 "Gallery" : "https://twosundowners.com/photo-Gallery/Gallery/road-to-bulgaria/#album"}},
{"lat": 45.535054, 
 "lon": 25.218013,
 "name": "Piatra Craiului, Romania",
 "country" : "642",
 "posts" : 
 {"Nature": "https://twosundowners.com/piatra-craiului/",
 "Climbing" : "https://twosundowners.com/Climbing-in-romania/",
 "Gallery" : "https://twosundowners.com/photo-Gallery/Gallery/piatra-craiului/#album"}},
{"lat" : 45.498800, 
 "lon" : 25.578403, 
 "name" : "Predeal, Romania",
 "country" : "642",
 "posts" : {
 "General" : "https://twosundowners.com/road-to-bulgaria/",
 "Gallery" : "https://twosundowners.com/photo-Gallery/Gallery/road-to-bulgaria/#album"}},
{"lat" : 44.435779, 
 "lon" : 26.097375, 
 "name" : "Bucharest, Romania",
 "country" : "642",
 "posts" : {
 "General" : "https://twosundowners.com/road-to-bulgaria/",
 "City" : "https://twosundowners.com/road-to-bulgaria/",
 "Climbing" : "https://twosundowners.com/Climbing-in-romania/",
 "Gallery" : "https://twosundowners.com/photo-Gallery/Gallery/road-to-bulgaria/#album"}},
{"lat" : 43.077798,
 "lon" : 25.629002, 
 "name" : "Veliko Tarnovo, Bulgaria",
 "country" : "100",
 "posts" : {
 "City": "https://twosundowners.com/veliko-tarnovo/",
 "Nature": "https://twosundowners.com/veliko-tarnovo/",
 "Running": "https://twosundowners.com/veliko-tarnovo/",
 "Food": "https://twosundowners.com/veliko-tarnovo/",
 "Gallery" : "https://twosundowners.com/photo-Gallery/Gallery/veliko-tarnovo/#album"}},
{"lat" : 43.175791, 
 "lon" : 24.073860, 
 "name" : "Prohodna Cave, Bulgaria",
 "country" : "100",
 "posts" : {
 "Gallery" : "https://twosundowners.com/photo-Gallery/Gallery/prohodna-cave-karlukovo/#album"}},
{"lat" : 43.627028,
 "lon" : 22.679694, 
 "name" : "Belogradchik, Bulgaria",
 "country" : "100",
 "posts" : {
 "General" : "https://twosundowners.com/belogradchik-vratsa/",
 "Gallery" : "https://twosundowners.com/photo-Gallery/Gallery/vratsa-belogradchik/#album"}},
{"lat" : 43.213010,
 "lon" : 23.546738, 
 "name" : "Vratsa, Bulgaria",
 "country" : "100",
 "posts" : {
 "General" : "https://twosundowners.com/belogradchik-vratsa/",
 "Gallery" : "https://twosundowners.com/photo-Gallery/Gallery/vratsa-belogradchik/#album"}},
{"lat" : 42.705439,
 "lon" : 23.297158, 
 "name" : "Sofia, Bulgaria",
 "country" : "100",
 "posts" : {
 "City" : "https://twosundowners.com/sofia/",
 "Guide" : "https://twosundowners.com/sofia/",
 "Food" : "https://twosundowners.com/sofia/",
 "Gallery" : "https://twosundowners.com/photo-Gallery/Gallery/sofia/#album"}},
{"lat" : 42.133314, 
 "lon" : 23.549659, 
 "name" : "Rila, Bulgaria",
 "country" : "100",
 "posts" : {
 "Nature" : "https://twosundowners.com/rila/",
 "Gallery" : "https://twosundowners.com/photo-Gallery/Gallery/rila-mountains/#album"}},
{"lat" : 42.271949,
 "lon" : 23.604295, 
 "name" : "Borovets, Bulgaria",
 "country" : "100",
 "posts" : {
 "Nature" : "https://twosundowners.com/rila/",
 "Gallery" : "https://twosundowners.com/photo-Gallery/Gallery/rila-mountains/#album"}},
{"lat" : 42.146136,
 "lon" : 24.741558, 
 "name" : "Plovdiv, Bulgaria",
 "country" : "100",
 "posts" : {
 "City" : "https://twosundowners.com/plovdiv/",
 "Running" : "https://twosundowners.com/plovdiv/",
 "Gallery" : "https://twosundowners.com/photo-Gallery/Gallery/plovdiv/#album"}},
{"lat" : 41.838192,
 "lon" : 23.492494, 
 "name" : "Bansko, Bulgaria",
 "country" : "100",
 "posts" : {
 "Running" : "https://twosundowners.com/bansko/",
 "General" : "https://twosundowners.com/bansko/",
 "Gallery" : "https://twosundowners.com/photo-Gallery/Gallery/bansko/#album"}},
{"lat" : 41.940874,
 "lon" : 21.304953, 
 "name" : "Matka Canyon, Macedonia",
 "country" : "807",
 "posts" : {
 "Nature" : "https://twosundowners.com/skopje/",
 "Gallery" : "https://twosundowners.com/photo-Gallery/Gallery/skopje/#album"}},
{"lat" : 42.005702,
 "lon" : 21.435874, 
 "name" : "Skopje, Macedonia",
 "country" : "807",
 "posts" : {
 "City" : "https://twosundowners.com/skopje/",
 "Gallery" : "https://twosundowners.com/photo-Gallery/Gallery/skopje/#album"}},
{"lat" : 42.217693,
 "lon" : 20.721379,
 "name" : "Prizren, Kosovo", 
 "country" : "-99",
 "posts" : {
 "City" : "https://twosundowners.com/prizren/"}},
{"lat" : 42.450726,
 "lon" : 19.889191,
 "name" : "Valbone Valley, Albania",
 "country" : "008",
 "posts" : {
 "Nature" : "https://twosundowners.com/valbone-valley/",
 "Running" : "https://twosundowners.com/valbone-valley/",
 "Food" : "https://twosundowners.com/valbone-valley/",
 "Gallery" : "https://twosundowners.com/photo-Gallery/Gallery/valbone-valley/#album"}},
{"lat" : 42.058600,
 "lon" : 19.505837,
 "name" : "Shkodra, Albania",
 "country" : "008",
 "posts" : {
 "City" : "https://twosundowners.com/albania/",
 "Gallery" : "https://twosundowners.com/photo-Gallery/Gallery/mask-factory-shkodra/#album"}},
{"lat" : 42.424350,
 "lon" : 18.771442,
 "name" : "Kotor, Montenegro",
 "country" : "499",
 "posts" : {
 "City" : "https://twosundowners.com/montenegro/",
 "Running" : "https://twosundowners.com/montenegro/",
 "Gallery" : "https://twosundowners.com/photo-Gallery/Gallery/montenegro/#album"}},
{"lat" : 42.289454,
 "lon" : 18.841132,
 "name" : "Budva, Montenegro",
 "country" : "499",
 "posts" : {
 "City" : "https://twosundowners.com/montenegro/",
 "Gallery" : "https://twosundowners.com/photo-Gallery/Gallery/montenegro/#album"}},
{"lat" : 42.205771,
 "lon" : 18.945038, 
 "name" : "Petrovac, Montenegro",
 "country" : "499",
 "posts" : {
 "Running" : "https://twosundowners.com/montenegro/",
 "Gallery" : "https://twosundowners.com/photo-Gallery/Gallery/montenegro/#album"}},
{"lat" : 42.654811,
 "lon" : 18.104529,
 "name" : "Dubrovnik, Croatia",
 "country" : "191",
 "posts" : {
 "City" : "https://twosundowners.com/dubrovnik/",
 "Guide" : "https://twosundowners.com/dubrovnik/",
 "Gallery" : "https://twosundowners.com/photo-Gallery/Gallery/dubrovnik/#album"}},
{"lat" : 43.346918, 
 "lon" : 17.809567, 
 "name" : "Mostar, Bosna & Herzegovina",
 "country" : "070",
 "posts" : {
 "City" : "https://twosundowners.com/week-bosnia-herzegovina/",
 "Running" : "https://twosundowners.com/week-bosnia-herzegovina/",
 "Gallery" : "https://twosundowners.com/photo-Gallery/Gallery/bosnia-and-herzegowina/#album"}},
{"lat" : 43.858000,
 "lon" : 18.382982,
 "name" : "Sarajevo, Bosna & Herzegovina",
 "country" : "070",
 "posts" : {
 "City" : "https://twosundowners.com/week-bosnia-herzegovina/"}},
{"lat" : 48.734575, 
 "lon" : 9.314098, 
 "name" : "Esslingen, Germany",
 "country" : "276",
 "posts" : {}},
{"lat" : 47.070191, 
 "lon" : 14.300150, 
 "name" : "Sankt Lambrecht, Austria",
 "country" : "040",
 "posts" : {}},
{"lat" : 28.458773, 
"lon" : -81.390048, 
"name" : "Orlando, FL", 
"country" : "840",
"posts" : {
"General": "https://twosundowners.com/journey-to-lima/"}},
{"lat" : -12.133251,
 "lon" : -77.028710,
  "name" : "Lima, Peru",
  "country" : "604",
  "posts" : {
  "Food" : "https://twosundowners.com/vegetarian-Guide-lima/",
  "Guide" : "https://twosundowners.com/peru-car-rental/",
  "Guide" : "https://twosundowners.com/one-month-in-lima/"}},
{"lat" : -13.838349,
 "lon" : -76.250924,
  "name" : "Paracas, Peru",
  "country" : "604",
  "posts" : {
  "Nature" : "https://twosundowners.com/paracas/",
  "Guide" : "https://twosundowners.com/paracas/",
  "Gallery" : "https://twosundowners.com/photo-Gallery/Gallery/paracas-peru/#album"}},
{"lat" : -14.087867,
 "lon" : -75.764877,
  "name" : "La Huacachina, Peru",
  "country" : "604",
  "posts" : {
  "Guide" : "https://twosundowners.com/la-huacachina-sandy-paradise-foreigners/"}},
{"lat" : -16.490746, 
 "lon" : -68.143358, 
 "name" : "La Paz, Bolivia",
 "country" : "068",
 "posts" : {
 	"Guide" : "https://twosundowners.com/la-paz-10-things/",
 	"Food" : "https://twosundowners.com/vegetarians-guide-la-paz/",
 	"Running" : "https://twosundowners.com/bolivia-running/"
 	}},
{"lat" : -20.337464, 
 "lon" : -67.570242, 
 "name" : "Salar de Uyuni, Bolivia",
 "country" : "068",
 "posts" : {
 	"General" : "https://twosundowners.com/salt-flats/"
 }},
 {"lat" : -16.171329, 
 "lon" : -68.230677, 
 "name" : "Condoriri, Bolivia",
 "country" : "068",
 "posts" : {
 	"Running" : "https://twosundowners.com/bolivia-running/"
 }},
 {"lat" : -16.163977,
 "lon" :  -69.086814, 
 "name" : "Copacabana, Bolivia",
 "country" : "068",
 "posts" : {
 	"Running" : "https://twosundowners.com/bolivia-running/"
 }},
 {"lat" : -15.848505, 
 "lon" : -70.021054, 
 "name" : "Puno, Peru",
 "country" : "604",
 "posts" : {}},
 {"lat" : -13.514655, 
 "lon" : -71.980451, 
 "name" : "Cusco, Peru",
 "country" : "604",
 "posts" : {
 	"General" : "https://twosundowners.com/digital-nomad-cusco/"
 	}},
 {"lat" : -13.156058, 
 "lon" : -72.526524, 
 "name" : "Salkantay & Machu Picchu, Peru",
 "country" : "604",
 "posts" : {
 	"General" : "https://twosundowners.com/salkantay-trek/",
 	"Gallery" : "https://twosundowners.com/photo-gallery/gallery/salkantay-machu-picchu/#album"
 }},
 {"lat" : -13.259986, 
 "lon" : -72.267283, 
 "name" : "Ollantaytambo, Peru",
 "country" : "604",
 "posts" : {
 	"Guide" : "https://twosundowners.com/ollantaytambo/",
 	"Gallery" : "https://twosundowners.com/photo-gallery/gallery/1769/#album"
 	}},
 {"lat" : -13.790552, 
 "lon" : -71.232811, 
 "name" : "Ausangate massif, Peru",
 "country" : "604",
 "posts" : {}},
 {"lat" : -13.106740, 
 "lon" : -72.045081, 
 "name" : "Lares, Peru",
 "country" : "604",
 "posts" : {}},
 {"lat" : -13.311414, 
 "lon" : -72.028161, 
 "name" : "Huaran, Peru",
 "country" : "604",
 "posts" : {}},
];


var visited_countries = ["752", "578", "703", "642", "100",
						 "008", "807", "070", "040", "604",
						 "068", "840", "276", "826", "-99", 
						 "499", "191"];
						 
var post_cats = [{"name" : "General", 
				  "url" : "img/Guide.jpg"},
				 {"name" : "Guide" , 
				  "url" : "img/Guide.jpg"},
				 {"name" : "Running" , 
				  "url" : "img/Running.jpg"},
				 {"name" : "Food" , 
				  "url" : "img/Food.jpg"},
				 {"name" : "Climbing" , 
				  "url" : "img/Climbing.jpg"},
				 {"name" : "Nature" , 
				  "url" : "img/Nature.jpg"},
				 {"name" : "Gallery" , 
				  "url" : "img/Gallery.jpg"}];
				  
var icon_links = {"General" : "img/Guide.jpg",
				  "Guide" : "img/Guide.jpg",
				  "Running" : "img/Running.jpg",
				  "Food" : "img/Food.jpg",
				  "Climbing" : "img/Climbing.jpg",
				  "Nature" : "img/Nature.jpg",
				  "Gallery" : "img/Gallery.jpg"};
				 
				 
				 
				 